#!/bin/bash -       
#description     :
#author          :Michele Gazzetti
#date            :09.06.16
#notes           :
#==============================================================================


#####
### Wlan to eth connection 
### pc connected to wlan
### pc-eth0 <---> eth0-rpi
#####

#### test this version and see if it works (probably not)
#
#sudo sysctl -w net.ipv4.ip_forward=1
#sudo iptables -A FORWARD --in-interface eth0 -j ACCEPT
#sudo iptables --table nat -A POSTROUTING --out-interface wlan0 -j MASQUERADE
#sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
#sudo sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf
#docker run --name raspbian -it sdhibit/rpi-raspbian:latest /bin/bash
#git clone https://github.com/sdhibit/docker-rpi-raspbian
#sudo apt-get install debootstrap
#docker rmi $(docker images -q)
#sudo brctl addbr br0

### this version should work
echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE

ifconfig eth0 10.0.0.1 netmask 255.255.255.0 up

sudo apt-get install isc-dhcp-server

#in /etc/dhcp/dhcpd.conf
subnet 10.0.0.0 netmask 255.255.255.0 {
    interface eth0;
    range 10.0.0.100 10.0.0.120;
    option routers 10.0.0.1;
    option domain-name-servers the-ip-address-you-have-in-etc-resolv.conf;
}

#Use sed to change file: sudo sed -i "s/#INTERFACES="eth0"/INTERFACES="eth0"/g" /etc/default/isc-dhcp-server
# in /etc/default/isc-dhcp-server
INTERFACES="eth0"

sudo dhcpd start

####
