#!/bin/bash -       
#description     :docker setup
#author          :Michele Gazzetti
#date            :14.04.16
#notes           :
#==============================================================================

###
## Docker configuration
###
#
sudo apt-get update

sudo apt-get install apt-transport-https ca-certificates -y

sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609

sudo su -c "echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list"
#
sudo apt-get update
#
sudo apt-get purge lxc-docker

apt-cache policy docker-engine

sudo apt-get update

sudo apt-get install linux-image-extra-$(uname -r) apparmor

sudo apt-get update
#
sudo sed -i.bak '/^#SYS_GID_MIN/c\SYS_GID_MIN 100' /etc/login.defs 
#
sudo sed -i '/^#SYS_GID_MAX/c\SYS_GID_MAX 999' /etc/login.defs 
#
sudo apt-get install docker-engine -y --force-yes

sudo groupadd docker

sudo gpasswd -a ${USER} docker

sudo service docker restart

