#!/bin/bash -       
#description     : java setup
#author          :Michele Gazzetti
#date            :27.06.16
#notes           :
#==============================================================================


write_variable(){
    presence=$(cat ~/.profile | grep "export $1" )

    # if not present of comment --> add variable
    if [[ $presence != "" && $presence != "#*" ]]; then
        sed /"export $1"/d ~/.profile > .profile
        mv .profile ~/.profile
    fi

    echo "export $1=$2" >> ~/.profile
}


write_slash_bin(){
    #delete PATH=$VARIABLE/bin...
    presence=$(cat ~/.profile | grep "PATH=\$$1" )

    if [[ $presence != "" && $presence != "#*" ]]; then
        sed /"PATH=\$$1"/d ~/.profile  > .profile
        mv .profile ~/.profile
    fi
    echo "PATH=\$$1/bin:\$PATH" >> ~/.profile
    #cat ~/.profile
}

write_variable_bin(){
    write_variable $1 $2
    write_slash_bin $1
}

#download java jkd
#http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz" -P /tmp

mkdir /home/$USER/sw

tar xvzf /tmp/jdk-8u101-linux-x64.tar.gz -C /home/$USER/sw

#tar xzf jdk-7u79-linux-x64.tar.gz -C /opt

write_variable_bin JAVA_HOME /home/$USER/sw/jdk1.8.0_101
