#!/bin/bash -       
#description     : maven setup
#author          :Michele Gazzetti
#date            :27.06.16
#notes           :
#==============================================================================


write_variable(){
    presence=$(cat ~/.profile | grep "export $1" )

    # if not present of comment --> add variable
    if [[ $presence != "" && $presence != "#*" ]]; then
        sed /"export $1"/d ~/.profile > .profile
        mv .profile ~/.profile
    fi

    echo "export $1=$2" >> ~/.profile
}


write_slash_bin(){
    #delete PATH=$VARIABLE/bin...
    presence=$(cat ~/.profile | grep "PATH=\$$1" )

    if [[ $presence != "" && $presence != "#*" ]]; then
        sed /"PATH=\$$1"/d ~/.profile  > .profile
        mv .profile ~/.profile
    fi
    echo "PATH=\$$1/bin:\$PATH" >> ~/.profile
    #cat ~/.profile
}

write_variable_bin(){
    write_variable $1 $2
    write_slash_bin $1
}

###
## Maven setup  version: 3.3.9
###

#TODO: pass version as parameter

#
wget http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz -P /tmp
#
sudo tar xzf /tmp/apache-maven-3.3.9-bin.tar.gz -C /opt/

write_variable M2_REPO /home/"$USER"/.m2/repository
write_variable_bin M2_HOME /opt/apache-maven-3.3.9

echo "exe: source ~/.profile"
