#!/bin/bash -       
#description     :docker install script
#author          :Michele Gazzetti
#date            :14.04.16
#notes           :
#==============================================================================

### Variables
#script name --> for end message
SCRIPT_NAME=`basename "$0"`

### Inform the user that the script has finished
#notify-send "$SCRIPT_NAME" "$END_MESSAGE" 
#sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
##vim /etc/apt/sources.list.d/docker.list  --> wipe and insert deb https://apt.dockerproject.org/repo ubuntu-trusty main

#sudo su -c "echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list"

#sudo apt-get update

#sudo apt-get purge lxc-docker

#sudo apt-get autoremove

#apt-cache policy docker-engine

#sudo apt-get update

#sudo apt-get install linux-image-extra-$(uname -r)

#sudo apt-get install docker-engine

##sudo service docker start

#sudo groupadd docker

#sudo gpasswd -a ${USER} docker

wget -qO- https://get.docker.com/ | sh

sudo usermod -aG docker mgazz

sudo service docker restart

